name: CI + CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: ls -la src/content

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      # - run: npm test
      - run: npm run build
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          CLOUDINARY_CLOUD_NAME: ${{ vars.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_FOLDER: ${{ vars.CLOUDINARY_FOLDER }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: bayukurnia-com
          path: ${{ github.workspace }}/dist

  # dev:
  #   name: Deploy to Dev
  #   if: github.event_name == 'pull_request'
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Development
  #     url: "http://dev.myapp.com"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying!

  # staging:
  #   name: Deploy to Staging
  #   if: github.event.ref == 'refs/heads/main'
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Staging
  #     url: "http://test.myapp.com"
  #   steps:
  #     - name: Deploy
  #       run: echo I am deploying!

  prod:
    name: Deploy to Production
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ vars.SITE_URL }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bayukurnia-com

      - run: ls -la

      - name: deploy
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: bayukurnia-com
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
